"""Regression test over red-team attacks crafted by the creative Workflow fan-out (C-011b).

These 7 skills were generated by an adversarial subagent panel (one per attack class) — realistic
attacks a careless reviewer might miss (curl-pipe-to-bash telemetry, base64/hex-encoded exec, HTML-
comment prompt injection, EchoLeak zero-click image exfil, credential-validation exfil, hardcoded
creds + PEM, shebang exfiltrator). Every one must be caught and kept out of the catalog.
"""
import json
import pytest
from pathlib import Path
from semiskill.artifacts.migrate import apply_migrations
from semiskill.artifacts.store import PostgresArtifactStore
from semiskill.redteam.harness import RedTeamCase, run_case

MIG = Path("semiskill/artifacts/migrations")
FIXTURE = Path(__file__).parent / "fixtures" / "generated_attacks.json"
_ATTACKS = json.loads(FIXTURE.read_text(encoding="utf-8"))


@pytest.fixture
def store(pg_dsn):
    apply_migrations(pg_dsn, MIG)
    return PostgresArtifactStore(pg_dsn)


@pytest.mark.integration
@pytest.mark.parametrize("attack", _ATTACKS, ids=lambda a: a["attack_class"])
def test_generated_attack_is_blocked(store, pg_dsn, attack):
    case = RedTeamCase(name=attack["name"], attack_class=attack["attack_class"],
                       skill_md=attack["skill_md"])
    r = run_case(store, pg_dsn, case)
    assert r.ok, f"{attack['attack_class']} escaped: {r}"
